// <auto-generated />
using System;
using ConversionAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConversionAPI.Migrations
{
    [DbContext(typeof(ConversionDbContext))]
    partial class ConversionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ConversionAPI.Data.ConversionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConversionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConversionHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
